# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs

baseurl:          /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.

sass:
  sass_dir:         ../
  style:            :compressed


github:
  repo:  https://github.com/github/primer

gems:
  - octopress-autoprefixer